### ISSUE TITLE
Dynamically change colors ?

### ISSUE THREAD

**Issue by Alexisgt01** [creotip/vue-particles#69]
Hello,

I just saw that the project is indeed abandoned. I may be using the other version shortly, and thank you again for your work, it's great

I just have a quick question regarding this project, can we dynamically change the component colors without memory leaks using `key` from vuejs ?

Demo : https://alexisgatuingt.fr/home

If I change the color (with the pen icon at the bottom right), I have to reload my component by changing the page to see the change

You can find the Home Page about this website here : https://github.com/Alexisgt01/vuefolio/blob/master/src/views/Home.vue

Finally, if I use the `key` property of vuejs, I have a big memory leak, the component loads every time the color changes.

You may have a troubleshooting solution while waiting for the update on the other repository

Thanks again for your awesome work

Alexis

**Comment by matteobruni** [comment]
Hi @Alexisgt01, as you noticed this project is abandoned... You can checkout the Vue component of tsParticles (started from Particles.js): https://github.com/matteobruni/tsparticles/blob/master/components/vue/README.md

It has a breaking change since the Vue component uses the full config instead of some properties but at least has no memory leaks

**Comment by lindelof** [comment]
Oh, this project is a great project, I don't think it is abandoned. Please respect the author
